make diff between 7 and 9

diff --git a/SOURCES/bitrix-env/etc/ansible/library/bx_blockinfile b/SOURCES/bitrix-env/etc/ansible/library/bx_blockinfile
--- a/SOURCES/bitrix-env/etc/ansible/library/bx_blockinfile
+++ b/SOURCES/bitrix-env/etc/ansible/library/bx_blockinfile
@@ -1,6 +1,7 @@
-#!/bin/bash
+#!/usr/bin/bash
+#
 # insert block of line into the file
-
+#
 export LANG=en_EN.UTF-8
 export PATH=$PATH:/sbin:/usr/sbin
 
@@ -11,38 +12,32 @@ LOG=$TMP/bx_blocklines.log
 
 debug() {
     msg=$1
-
     [[ $DEBUG -gt 1  ]] && printf "%s: %d: %s\n" "$(date +%F-%H-%M-%S)" "$$" "$msg" >> $LOG
 }
 
 # print error message
 print_error() {
-  msg=$1
-  echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
-  exit 1
+    msg=$1
+    echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
+    exit 1
 }
 
 # print timezone info
 print_ok() {
-  msg=$1
-
-  echo "{\"changed\":true,\"msg\":\"$msg\"}"
-  exit 0
+    msg=$1
+    echo "{\"changed\":true,\"msg\":\"$msg\"}"
+    exit 0
 }
 
 print_notchanged() {
-  msg=$1
-
-  echo "{\"changed\":false,\"msg\":\"$msg\"}"
-  exit 0
-
+    msg=$1
+    echo "{\"changed\":false,\"msg\":\"$msg\"}"
+    exit 0
 }
 
-update_file(){
-
+update_file() {
     [[ -z $from_file ]] && print_error "No defined the file with block of strings from_file= opt."
-    insertafter_line=$(grep -n "$insertafter" $dest | \
-        head -n 1 | awk -F':' '{print $1}')
+    insertafter_line=$(grep -n "$insertafter" $dest | head -n 1 | awk -F':' '{print $1}')
     if [[ -z $insertafter_line ]]; then
         print_error "Not found insertafter=$insertafter in the file=$dest"
     fi
@@ -56,17 +51,15 @@ update_file(){
     print_ok "Update file dest=$dest"
 }
 
-delete_file(){
-    insertafter_line=$(grep -n "$insertafter" $dest | \
-        head -n 1 | awk -F':' '{print $1}')
+delete_file() {
+    insertafter_line=$(grep -n "$insertafter" $dest | head -n 1 | awk -F':' '{print $1}')
     if [[ -z $insertafter_line ]]; then
         print_notchanged "Not found insertafter=$insertafter in the file=$dest"
     fi
 
     [[ -z $insertbefore ]] && insertbefore="${insertafter}" 
 
-    insertbefore_line=$(grep -n "$insertbefore" $dest | \
-        tail -n 1 | awk -F':' '{print $1}')
+    insertbefore_line=$(grep -n "$insertbefore" $dest | tail -n 1 | awk -F':' '{print $1}')
     if [[ -z $insertbefore_line ]]; then
         print_notchanged "Not found insertafter=$insertbefore_line in the file=$dest"
     fi
@@ -79,10 +72,9 @@ delete_file(){
     print_ok "Update file dest=$dest"
 }
 
-dest_link(){
+dest_link() {
     if [[ -L $dest ]]; then
-        orig_file=$(file $dest | \
-            grep "symbolic link to" | awk -F'`' '{print $2}' | sed -e "s/'$//" )
+        orig_file=$(file $dest | grep "symbolic link to" | awk -F'`' '{print $2}' | sed -e "s/'$//" )
         dest="$orig_file"
     fi
 }
@@ -103,8 +95,8 @@ dn_dest=$(dirname "$dest")
 tmp_dest="${dn_dest}/$(date +%s)_${bn_dest}"
 
 case "$state" in
-    "update") update_file;;
-    "delete") delete_file;;
-    *) print_error "Unknown state option";;
+    "update") update_file ;;
+    "delete") delete_file ;;
+    *) print_error "Unknown state option" ;;
 esac
 
diff --git a/SOURCES/bitrix-env/etc/ansible/library/bx_db b/SOURCES/bitrix-env/etc/ansible/library/bx_db
--- a/SOURCES/bitrix-env/etc/ansible/library/bx_db
+++ b/SOURCES/bitrix-env/etc/ansible/library/bx_db
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/usr/bin/bash
+#
 # create dump for database and upload it to local mysql
 # src=          server with source of db ( ip address or unix socket )
 # dst=          server with destination of db  
@@ -6,9 +7,9 @@
 # login=        login for connection
 # password=     password
 # Carefully! Ansible already provides values in quotes
-
+#
 #set -e
-
+#
 BY_TABLE=1      # if set to 1 it is create dump per table
                 # Longer but more reliable for large databases
 REPLACE=0       # relace destionation database or not
@@ -26,59 +27,53 @@ TMPFILE=$TMPDIR/.bx_db
 
 # test mandatory option and print error if not exists
 test_variables() {
-  [[ -z $db ]] && db=mysql
-  if [[ ( -z $login ) && ( -z $password ) ]]; then
-    if [[ -f $DEFAULT_CONF ]]; then
-      DEFAULT_CONF_USAGE=1
+    [[ -z $db ]] && db=mysql
+    if [[ ( -z $login ) && ( -z $password ) ]]; then
+	if [[ -f $DEFAULT_CONF ]]; then
+	    DEFAULT_CONF_USAGE=1
+	else
+	    # create config with empty root
+	    echo "# test mysql conf" > $DEFAULT_CONF
+	    echo "[mysqld]"  >> $DEFAULT_CONF
+	    echo "user=root" >> $DEFAULT_CONF
+	    echo "password=" >> $DEFAULT_CONF
+	    echo >> $DEFAULT_CONF
+	    chmod 640 $DEFAULT_CONF
+	    # test default
+	    mysql -e 'select 1;' 1>/dev/null 2>&1
+	    if [[ $? -gt 0 ]]; then
+		echo "{\"changed\":false,\"failed\":true,\"msg\":\"option $var= is mandatory, you must define it or set in $DEFAULT_CONF file\"}"
+		rm -f $DEFAULT_CONF
+		exit 1
+	    fi
+	    DEFAULT_CONF_USAGE=1
+	fi
     else
-      # create config with empty root
-      echo "# test mysql conf" > $DEFAULT_CONF
-      echo "[mysqld]"  >> $DEFAULT_CONF
-      echo "user=root" >> $DEFAULT_CONF
-      echo "password=" >> $DEFAULT_CONF
-      echo >> $DEFAULT_CONF
-      chmod 640 $DEFAULT_CONF
-
-      # test default
-      mysql -e 'select 1;' 1>/dev/null 2>&1
-      if [[ $? -gt 0 ]]; then
-        echo "{\"changed\":false,\"failed\":true,\"msg\":\"option $var= is mandatory, you must define it or set in $DEFAULT_CONF file\"}"
-        rm -f $DEFAULT_CONF
-        exit 1
-      fi
-      DEFAULT_CONF_USAGE=1
+	login=root
+	MYSQLCMD=$MYSQLCMD" --user=$login --password='$password'"
     fi
-  else
-    login=root
-    MYSQLCMD=$MYSQLCMD" --user=$login --password='$password'"
-  fi
 }
 
 get_db_list() {
-  # test if mysql running
-  system_process=$(ps -ef | grep -w 'mysqld' | grep -vw grep | grep -vwc $$)
-  if [[ $system_process -gt 0 ]]; then 
-
-    $MYSQLCMD --skip-column-names -e "show databases;" | \
-      grep -vw 'information_schema\|performance_schema\|mysql\|test' | \
-      grep -v '#mysql' >$TMPFILE 2>&1
-    if [[ $? -gt 0 ]]; then
-      echo "{\"changed\":false,\"failed\":true,\"msg\":\"mysql cmd return error $(head $TMPFILE)\"}"
-      rm -f $TMPFILE
-      exit 1
+    # test if mysql running
+    system_process=$(ps -ef | grep -w 'mysqld' | grep -vw grep | grep -vwc $$)
+    if [[ $system_process -gt 0 ]]; then 
+	$MYSQLCMD --skip-column-names -e "show databases;" | grep -vw 'information_schema\|performance_schema\|mysql\|test' | grep -v '#mysql' >$TMPFILE 2>&1
+	if [[ $? -gt 0 ]]; then
+	    echo "{\"changed\":false,\"failed\":true,\"msg\":\"mysql cmd return error $(head $TMPFILE)\"}"
+	    rm -f $TMPFILE
+	    exit 1
+	fi
+	dbs_list=$(grep -vw "$db" $TMPFILE| awk '{printf "\"%s\",", $1}' | sed -e 's/,$//;')
+    else
+	dbs_list=""
     fi
-
-    dbs_list=$(grep -vw "$db" $TMPFILE| awk '{printf "\"%s\",", $1}' | sed -e 's/,$//;')
-  else
-    dbs_list=""
-  fi
     dbs_out="{\"ansible_facts\":{"
     dbs_out=$dbs_out"\"dbs_list\":["
     dbs_out=$dbs_out$dbs_list
     dbs_out=$dbs_out"]}}"
     echo $dbs_out
 }
-
 
 # get options from file
 source ${1}
diff --git a/SOURCES/bitrix-env/etc/ansible/library/bx_etckeeper b/SOURCES/bitrix-env/etc/ansible/library/bx_etckeeper
--- a/SOURCES/bitrix-env/etc/ansible/library/bx_etckeeper
+++ b/SOURCES/bitrix-env/etc/ansible/library/bx_etckeeper
@@ -1,6 +1,7 @@
-#!/bin/bash
+#!/usr/bin/bash
+#
 # insert block of line into the file
-
+#
 export LANG=en_EN.UTF-8
 export PATH=$PATH:/sbin:/usr/sbin
 
@@ -11,42 +12,36 @@ LOG=$TMP/bx_blocklines.log
 
 debug() {
     msg=$1
-
     [[ $DEBUG -gt 1  ]] && printf "%s: %d: %s\n" "$(date +%F-%H-%M-%S)" "$$" "$msg" >> $LOG
 }
 
 # print error message
 print_error() {
-  msg=$1
-  echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
-  if [[ -f $TMPFILE && $DEBUG -eq 0 ]]; then
-      rm -f $TMPFILE
-  fi
-  exit 1
+    msg=$1
+    echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
+    if [[ -f $TMPFILE && $DEBUG -eq 0 ]]; then
+	rm -f $TMPFILE
+    fi
+    exit 1
 }
 
 # print timezone info
 print_ok() {
-  msg=$1
-
-  echo "{\"changed\":true,\"msg\":\"$msg\"}"
-  if [[ -f $TMPFILE && $DEBUG -eq 0 ]]; then
-      rm -f $TMPFILE
-  fi
- 
-  exit 0
+    msg=$1
+    echo "{\"changed\":true,\"msg\":\"$msg\"}"
+    if [[ -f $TMPFILE && $DEBUG -eq 0 ]]; then
+	rm -f $TMPFILE
+    fi
+    exit 0
 }
 
 print_notchanged() {
-  msg=$1
-
-  echo "{\"changed\":false,\"msg\":\"$msg\"}"
-  if [[ -f $TMPFILE && $DEBUG -eq 0 ]]; then
-      rm -f $TMPFILE
-  fi
- 
-  exit 0
-
+    msg=$1
+    echo "{\"changed\":false,\"msg\":\"$msg\"}"
+    if [[ -f $TMPFILE && $DEBUG -eq 0 ]]; then
+	rm -f $TMPFILE
+    fi
+    exit 0
 }
 
 revert_commit() {
@@ -55,14 +50,10 @@ revert_commit() {
     # get mercurial history
     hg log | grep '^\(changeset\|summary\):' > $TMPFILE 2>&1
     for rtn in ${PIPESTATUS[*]}; do
-        [[ $rtn -gt 0 ]] && \
-            error "Cannot get hg log for /etc"
+        [[ $rtn -gt 0 ]] && error "Cannot get hg log for /etc"
     done
-
     # get changeset number
-    CHANGESET=$(cat $TMPFILE | grep "$commit" -B1 | \
-        tail -n 2 | grep "^changeset:" | \
-        awk -F':' '{print $2}' | sed -e "s/\s\+//")
+    CHANGESET=$(cat $TMPFILE | grep "$commit" -B1 | tail -n 2 | grep "^changeset:" | awk -F':' '{print $2}' | sed -e "s/\s\+//")
     if [[ $CHANGESET -gt 0 ]] 2>/dev/null; then
         hg revert -r $CHANGESET $dest > $TMPFILE 2>&1
         hg_rtn=$?
@@ -74,7 +65,6 @@ revert_commit() {
     else
         print_notchanged "Not found commit=$commit"
     fi
-
     popd >/dev/null 2>&1
 }
 
@@ -87,7 +77,7 @@ source ${1} 2>/dev/null
 debug "commit=$commit state=$state"
 
 case "$state" in
-    "revert") revert_commit;;
-    *) print_error "Unknown state option";;
+    "revert") revert_commit ;;
+    *) print_error "Unknown state option" ;;
 esac
 
diff --git a/SOURCES/bitrix-env/etc/ansible/library/bx_perf b/SOURCES/bitrix-env/etc/ansible/library/bx_perf
--- a/SOURCES/bitrix-env/etc/ansible/library/bx_perf
+++ b/SOURCES/bitrix-env/etc/ansible/library/bx_perf
@@ -1,6 +1,8 @@
-#!/bin/bash
-#   Generate performance options for configs
+#!/usr/bin/bash
+#
+# Generate performance options for configs
 #set -x
+#
 export LANG=en_EN.UTF-8
 export NOLOCALE=yes
 export PATH=/sbin:/bin:/usr/sbin:/usr/bin
@@ -14,48 +16,38 @@ VARS80="table_open_cache;thread_cache_size;max_heap_table_size;tmp_table_size;ke
 MYSQL_CONFIG=/etc/mysql/conf.d/bvat.cnf
 MYSQL_CONFIG_TEMPLATE=/etc/ansible/templates/bx_perf-bvat.cnf.j2
 MYSQL_CONFIG_TEMPLATE80=/etc/ansible/templates/bx_perf-bvat_my80.cnf.j2
- 
-OS_VERSION=$(cat /etc/redhat-release | \
-    sed -e "s/CentOS Linux release//;s/CentOS release // " | cut -d'.' -f1)
+OS_VERSION=$(cat /etc/redhat-release | sed -e "s/CentOS Stream release//;s/CentOS release // " | cut -d'.' -f1)
 
-
-error(){
+error() {
     msg="$1"
     echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
     exit 1
 }
 
-get_column_number(){
+get_column_number() {
     name="${1}"
     [[ -z $name ]] && error "get_column_number; you must define column name"
 
-    num=$(head -1 $PERF  | \
-        awk -F';' ' { for (i = 1; i <= NF; ++i) printf "%d:%s\n", i, $i; exit  }' | \
-        grep ":$name$" | awk -F':' '{print $1}')
+    num=$(head -1 $PERF | \
+	awk -F';' ' { for (i = 1; i <= NF; ++i) printf "%d:%s\n", i, $i; exit  }' | \
+	grep ":$name$" | awk -F':' '{print $1}')
     [[ -z $num ]] && error "get_column_number; not found column number for $name"
     return $num
 }
 
-get_os_type(){
+get_os_type() {
     OS_TYPE=$(cat /etc/redhat-release | grep CentOS -c)
-
-    OS_VERSION=$(cat /etc/redhat-release | \
-        sed -e "s/CentOS Linux release//;s/CentOS release // " | \
-        cut -d'.' -f1 |sed -e "s/\s\+//")
-
+    OS_VERSION=$(cat /etc/redhat-release | sed -e "s/CentOS Stream release//;s/CentOS release // " | cut -d'.' -f1 |sed -e "s/\s\+//")
     # is OpenVZ installation
     IS_OPENVZ=$( [[ -f /proc/user_beancounters  ]] && echo 1 || echo 0  )
-
     # Hardware type
     HW_TYPE=general
     [[ $IS_OPENVZ -gt 0  ]] && HW_TYPE=openvz
-
     # x86_64 or i386
     IS_X86_64=$(uname -a | grep -wc 'x86_64')
-
 }
 
-get_mysql_package(){
+get_mysql_package() {
     [[ -n $MYSQL_PACKAGE ]] && return 0
 
     PACKAGES_LIST=$(rpm -qa)
@@ -65,21 +57,17 @@ get_mysql_package(){
     if [[ $(echo "$PACKAGES_LIST" | grep -c '^mysql-community-server') -gt 0 ]]; then
         MYSQL_PACKAGE=mysql-community-server
         MYSQL_SERVICE=mysqld
-
     # Percona 5.6 && 5.7
     elif [[ $(echo "$PACKAGES_LIST" | grep -c '^Percona-Server-server') -gt 0 ]]; then
         MYSQL_PACKAGE=Percona-Server-server
         MYSQL_SERVICE=mysqld
-
     # Percona 8.0
     elif [[ $(echo "$PACKAGES_LIST" | grep -c '^percona-server-server') -gt 0  ]]; then
         MYSQL_PACKAGE=percona-server-server
         MYSQL_SERVICE=mysqld
-
     elif [[ $(echo "$PACKAGES_LIST" | grep -c '^MariaDB-server') -gt 0 ]]; then
         MYSQL_PACKAGE=MariaDB-server
         MYSQL_SERVICE=mariadb
-
     elif [[ $(echo "$PACKAGES_LIST" | grep -c '^mariadb-server') -gt 0 ]]; then
         MYSQL_PACKAGE=mariadb-server
         MYSQL_SERVICE=mariadb
@@ -89,47 +77,48 @@ get_mysql_package(){
     else
         return 1
     fi
-    MYSQL_VERSION=$(rpm -qa --queryformat '%{version}' ${MYSQL_PACKAGE}* | \
-        head -1 | awk -F'.' '{printf "%d.%d", $1,$2}' )
+    MYSQL_VERSION=$(rpm -qa --queryformat '%{version}' ${MYSQL_PACKAGE}* | head -1 | awk -F'.' '{printf "%d.%d", $1,$2}' )
     MYSQL_MID_VERSION=$(echo "$MYSQL_VERSION" | awk -F'.' '{print $2}')
     MYSQL_UNI_VERSION=$(echo "$MYSQL_VERSION" | awk -F'.' '{printf "%s%s", $1,$2}')
 
     # mysql status
     [[ -z $OS_VERSION ]] && get_os_type
     MYSQL_STATUS=
-    if [[ $OS_VERSION -eq 7 ]]; then
-        systemctl is-active $MYSQL_SERVICE >/dev/null 2>&1
+
+    # VMBITRIX_9.0
+    if [[ $OS_VERSION -eq 9 ]]; then
+        systemctl is-active $MYSQL_SERVICE > /dev/null 2>&1
+        status_rtn=$?
+    elif [[ $OS_VERSION -eq 7 ]]; then
+        systemctl is-active $MYSQL_SERVICE > /dev/null 2>&1
         status_rtn=$?
     else
         MYSQL_INIT_SCRIPT=/etc/init.d/mysqld
         MYSQL_SERVICE_NAME=mysqld
-
         if [[ -f /etc/init.d/mysql ]]; then
             MYSQL_INIT_SCRIPT=/etc/init.d/mysql
             MYSQL_SERVICE_NAME=mysql
         fi
-        $MYSQL_INIT_SCRIPT status | grep -wc running >/dev/null 2>&1
+        $MYSQL_INIT_SCRIPT status | grep -wc running > /dev/null 2>&1
         status_rtn=$?
     fi
+
     if [[ $status_rtn -gt 0 ]]; then
         MYSQL_STATUS="stopped"
     else
         MYSQL_STATUS="running"
     fi
-
 }
 
 # get available memory on board
-get_available_memory(){
+get_available_memory() {
     [[ -z $IS_X86_64 ]] && get_os_type
 
     AVAILABLE_MEMORY=$(free | grep Mem | awk '{print $2}')
     if [[ $IS_OPENVZ -gt 0 ]]; then
         if [[ -z $AVAILABLE_MEMORY ]]; then
-            mem4kblock=`cat /proc/user_beancounters | \
-                grep vmguarpages|awk '{print $4}'`
-            mem4kblock2=`cat /proc/user_beancounters | \
-                grep privvmpages|awk '{print $4}'`
+            mem4kblock=`cat /proc/user_beancounters | grep vmguarpages|awk '{print $4}'`
+            mem4kblock2=`cat /proc/user_beancounters | grep privvmpages|awk '{print $4}'`
             if [[ ${mem4kblock2} -gt ${mem4kblock} ]]; then
                 AVAILABLE_MEMORY=$(echo "${mem4kblock} * 4"|bc)
             else
@@ -140,63 +129,49 @@ get_available_memory(){
 
     AVAILABLE_MEMORY_MB=$(( $AVAILABLE_MEMORY / 1024 ))
 
-    [[ ( $IS_X86_64 -eq 0 ) && ( $AVAILABLE_MEMORY_MB -gt 4096 ) ]] && \
-        AVAILABLE_MEMORY_MB=4096
+    [[ ( $IS_X86_64 -eq 0 ) && ( $AVAILABLE_MEMORY_MB -gt 4096 ) ]] && AVAILABLE_MEMORY_MB=4096
 }
 
-get_memory_limits(){
+get_memory_limits() {
     get_column_number Memory
     memory_column=$?
     
-    MEMORY_LIMITS=$(cat $PERF | grep ";$HW_TYPE;" | \
-        awk -F';' -v col=$memory_column '{print $col}')
+    MEMORY_LIMITS=$(cat $PERF | grep ";$HW_TYPE;" | awk -F';' -v col=$memory_column '{print $col}')
     MIN_MEMORY_MB=0
-
     MAX_MB=
     for max_mb in $MEMORY_LIMITS; do
-        if [[ ( $AVAILABLE_MEMORY_MB -gt $MIN_MEMORY_MB ) && \
-             ( $AVAILABLE_MEMORY_MB -le $max_mb ) && ( -z $MAX_MB ) ]]; then
+        if [[ ( $AVAILABLE_MEMORY_MB -gt $MIN_MEMORY_MB ) && ( $AVAILABLE_MEMORY_MB -le $max_mb ) && ( -z $MAX_MB ) ]]; then
             MAX_MB=$max_mb
         fi
         MIN_MEMORY_MB=$max_mb
     done
     
     # maximum
-    [[ $AVAILABLE_MEMORY_MB -gt $max_mb ]] && \
-        MAX_MB=$max_mb
+    [[ $AVAILABLE_MEMORY_MB -gt $max_mb ]] && MAX_MB=$max_mb
 
     # minimum
     [[ -z $MAX_MB ]] && MAX_MB=512
 }
 
-get_mysql_options(){
-
+get_mysql_options() {
     # simple variables
     VARS_TEXT=
 
     for v in $(echo $VARS | sed -e "s/;/ /g"); do
-        [[ -n $VARS_TEXT ]] && \
-            VARS_TEXT="${VARS_TEXT},"
-
+        [[ -n $VARS_TEXT ]] && VARS_TEXT="${VARS_TEXT},"
         get_column_number $v
         p=$?
-
-        s=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | \
-            awk -F';' -v col=$p '{print $col}')
-
+        s=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | awk -F';' -v col=$p '{print $col}')
         VARS_TEXT="${VARS_TEXT}\"$v\":$s"
     done
 
     # max_connection
-    [[ -n $VARS_TEXT ]] && \
-        VARS_TEXT="${VARS_TEXT},"
+    [[ -n $VARS_TEXT ]] && VARS_TEXT="${VARS_TEXT},"
 
     get_column_number "PHP_threads"
     php_threads_col=$?
 
-    php_threads=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | \
-        awk -F';' -v col=$php_threads_col '{print $col}')
-
+    php_threads=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | awk -F';' -v col=$php_threads_col '{print $col}')
     max_connections=$(( $php_threads + 25 ))
     start_servers=$php_threads
 
@@ -205,17 +180,15 @@ get_mysql_options(){
     VARS_TEXT="${VARS_TEXT}\"max_connections\":$max_connections,"
     VARS_TEXT="${VARS_TEXT}\"https_servers\":$start_servers"
 
-
     # print ansible facts
     echo '{"ansible_facts":{'
     echo $VARS_TEXT
     echo '}}'
 }
 
-update_config(){
+update_config() {
     orig=${1}
     new=${2}
-
     # test md5 summ
     orig_md5_summ=0
     temp_md5_summ=$(md5sum $new | awk '{print $1}')
@@ -230,22 +203,16 @@ update_config(){
         rm -f $new
         echo "{\"changed\":false,\"msg\":\"Config $orig is ok\"}"
     fi
-
-
-
 }
 
-update_configs_mysql(){
+update_configs_mysql() {
     # update mysql config
     MYSQL_CONFIG_TMP=$MYSQL_CONFIG.tmp
     cp -f $MYSQL_CONFIG_TEMPLATE $MYSQL_CONFIG_TMP
     for v in $(echo $VARS | sed -e "s/;/ /g"); do
         get_column_number $v
         p=$?
-
-        s=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | \
-            awk -F';' -v col=$p '{print $col}')
-
+        s=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | awk -F';' -v col=$p '{print $col}')
         sed -i "s/{{\s*$v\s*}}/$s/" $MYSQL_CONFIG_TMP
     done
 
@@ -253,36 +220,32 @@ update_configs_mysql(){
     get_column_number "PHP_threads"
     php_threads_col=$?
 
-    php_threads=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | \
-        awk -F';' -v col=$php_threads_col '{print $col}')
-
+    php_threads=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | awk -F';' -v col=$php_threads_col '{print $col}')
     max_connections=$(( $php_threads + 25 ))
     start_servers=$php_threads
 
     sed -i "s/{{\s*max_connections\s*}}/$max_connections/" $MYSQL_CONFIG_TMP
     sed -i "s/{{\s*max_memory\s*}}/$MAX_MB/" $MYSQL_CONFIG_TMP
-   
 
     update_config "$MYSQL_CONFIG" "$MYSQL_CONFIG_TMP"
 }
 
-update_configs_apache(){
-
+update_configs_apache() {
     # update apache config
     APACHE_CONFIG=/etc/httpd/bx/conf/prefork.conf
     APACHE_CONFIG_TMP=$APACHE_CONFIG.tmp
     APACHE_CONFIG_TEMPLATE=/etc/ansible/templates/bx_perf-prefork22.conf.j2
-    [[ $OS_VERSION -eq 7 ]] && \
-        APACHE_CONFIG_TEMPLATE=/etc/ansible/templates/bx_perf-prefork24.conf.j2
+
+    # VMBITRIX_9.0
+    [[ $OS_VERSION -eq 9 ]] && APACHE_CONFIG_TEMPLATE=/etc/ansible/templates/bx_perf-prefork24.conf.j2
+    [[ $OS_VERSION -eq 7 ]] && APACHE_CONFIG_TEMPLATE=/etc/ansible/templates/bx_perf-prefork24.conf.j2
+
     cp -f $APACHE_CONFIG_TEMPLATE $APACHE_CONFIG_TMP
  
     # max_connection
     get_column_number "PHP_threads"
     php_threads_col=$?
-
-    php_threads=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | \
-        awk -F';' -v col=$php_threads_col '{print $col}')
-
+    php_threads=$(cat $PERF | grep ";$MAX_MB;$HW_TYPE;" | awk -F';' -v col=$php_threads_col '{print $col}')
     start_servers=$php_threads
 
     sed -i "s/{{\s*start_servers\s*}}/$start_servers/" $APACHE_CONFIG_TMP
@@ -298,8 +261,7 @@ else
     state="$opt"
 fi
 
-[[ ! -f $PERF ]] && \
-    error "Not found config file=$PERF"
+[[ ! -f $PERF ]] && error "Not found config file=$PERF"
 
 # get mysql info
 get_mysql_package
@@ -312,7 +274,7 @@ fi
 # get installed memory size
 get_available_memory
 
-# 
+# get memory limits
 get_memory_limits
 
 # generate config
diff --git a/SOURCES/bitrix-env/etc/ansible/library/bx_php b/SOURCES/bitrix-env/etc/ansible/library/bx_php
--- a/SOURCES/bitrix-env/etc/ansible/library/bx_php
+++ b/SOURCES/bitrix-env/etc/ansible/library/bx_php
@@ -1,23 +1,24 @@
-#!/bin/bash
+#!/usr/bin/bash
+#
 # get info disabled modules
 # options:
 # action=status
+#
 export LANG="en_US.UTF-8"
 LOG=/tmp/php_modules.list
 
 # print error message
 print_error() {
-  msg=$1
-  echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
-  exit 1
+    msg=$1
+    echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
+    exit 1
 }
 
 # print timezone info
 print_ok() {
-  msg=$1
-
-  echo "{\"changed\":true,\"msg\":\"$msg\",\"php_list\":\"$LOG\"}"
-  exit 0
+    msg=$1
+    echo "{\"changed\":true,\"msg\":\"$msg\",\"php_list\":\"$LOG\"}"
+    exit 0
 }
 
 # get ansible options
@@ -31,22 +32,22 @@ php_include_dir=/etc/php.d
 ## 5.4 upgrade
 # save modules wich disabled, but don't have empty one file (update created it)
 if [[ "$action" == "safe" ]]; then
-  echo -n > $LOG
-  for f_disabled in `find $php_include_dir/ -name "*.disabled" -type f`; do
-    f_ini=$(echo "$f_disabled" | sed -e 's:\.disabled$::')
-    echo "$f_ini"
-    [[ ! -f $f_ini ]] && echo $f_ini >> $LOG
-  done
-  print_ok "Save list files"
+    echo -n > $LOG
+    for f_disabled in `find $php_include_dir/ -name "*.disabled" -type f`; do
+	f_ini=$(echo "$f_disabled" | sed -e 's:\.disabled$::')
+	echo "$f_ini"
+	[[ ! -f $f_ini ]] && echo $f_ini >> $LOG
+    done
+    print_ok "Save list files"
 fi
 
 # disable modules and create empty files 
 if [[ ( "$action" == "restore" ) && ( -e $LOG ) ]]; then
-  while read file; do
-    mv -f $file ${file}.disabled
-    echo -n > $file
-  done < $LOG
-  print_ok "Restore files"
+    while read file; do
+	mv -f $file ${file}.disabled
+	echo -n > $file
+    done < $LOG
+    print_ok "Restore files"
 fi
 
 ## 5.6 upgrade
diff --git a/SOURCES/bitrix-env/etc/ansible/library/bx_php_extension b/SOURCES/bitrix-env/etc/ansible/library/bx_php_extension
--- a/SOURCES/bitrix-env/etc/ansible/library/bx_php_extension
+++ b/SOURCES/bitrix-env/etc/ansible/library/bx_php_extension
@@ -1,34 +1,32 @@
-#!/bin/bash
+#!/usr/bin/bash
+#
 # fix php errors
+#
 export LANG="en_US.UTF-8"
 export PATH=/usr/bin:/usr/sbin:/bin:/sbin
 TMPFILE=$(mktemp /tmp/php_extensions.XXXXX)
 
 # print error message
 print_error() {
-  msg=$1
-  echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
-  [[ -f $TMPFILE ]] && rm -f $TMPFILE
-  exit 1
+    msg=$1
+    echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
+    [[ -f $TMPFILE ]] && rm -f $TMPFILE
+    exit 1
 }
 
 # print timezone info
 print_changed() {
-  msg=$1
-
-  echo "{\"changed\":true,\"msg\":\"$msg\"}"
-  [[ -f $TMPFILE ]] && rm -f $TMPFILE
-
-  exit 0
+    msg=$1
+    echo "{\"changed\":true,\"msg\":\"$msg\"}"
+    [[ -f $TMPFILE ]] && rm -f $TMPFILE
+    exit 0
 }
 
 print_notchanged() {
-  msg=$1
-
-  echo "{\"changed\":false,\"msg\":\"$msg\"}"
-  [[ -f $TMPFILE ]] && rm -f $TMPFILE
-
-  exit 0
+    msg=$1
+    echo "{\"changed\":false,\"msg\":\"$msg\"}"
+    [[ -f $TMPFILE ]] && rm -f $TMPFILE
+    exit 0
 }
 
 
@@ -51,12 +49,9 @@ MODULES_CHANGED=
 MODULES_UNCHANGED=
 if [[ -n $DUBLICATE_MODULES ]]; then
     for mod in $DUBLICATE_MODULES; do
-        php_inis=$(find /etc/php.d/ -maxdepth 1 -type f -name "*.ini" \
-            -exec grep -H "^\s*extension=$mod" '{}' ';' | \
-            awk -F':' '{print $1}')
+        php_inis=$(find /etc/php.d/ -maxdepth 1 -type f -name "*.ini" -exec grep -H "^\s*extension=$mod" '{}' ';' | awk -F':' '{print $1}')
         if [[ -n $php_inis ]]; then
             MODULES_CHANGED="$MODULES_CHANGED $mod"
-
             remove_files_cnt=0
             remove_files=
             first_file=
@@ -71,7 +66,6 @@ if [[ -n $DUBLICATE_MODULES ]]; then
                     remove_files=$remove_files" $file"
                 fi
             done
-
             if [[ ( $remove_files_cnt -gt 0 ) ]]; then
                 if [[ $remove_files_cnt -lt $cnt ]]; then
                     rm -f $remove_files
diff --git a/SOURCES/bitrix-env/etc/ansible/library/time_facts b/SOURCES/bitrix-env/etc/ansible/library/time_facts
--- a/SOURCES/bitrix-env/etc/ansible/library/time_facts
+++ b/SOURCES/bitrix-env/etc/ansible/library/time_facts
@@ -1,100 +1,86 @@
-#!/bin/bash
+#!/usr/bin/bash
+#
 # get info about time zone and ntpd status
 # options:
 # action=status
+#
 export LANG="en_US.UTF-8"
 
-CFG_SYSCLOCK="/etc/sysconfig/clock" # file controls the interpretation of values read from the system hardware clock
-CFG_LOCALTIME="/etc/localtime"      # file configures the system-wide timezone of the local system
-                                    # that is used by applications for presentation to the user
-TZ_DB="/usr/share/zoneinfo"         # standart path for timezone database
-
-TZ_DEFAULT="UTC"          # default timezone ( use if not found the settings in the system )
-
-CFG_PHP="/etc/php.d/bitrixenv.ini"   # bitrixenv php file
+CFG_SYSCLOCK="/etc/sysconfig/clock"    # file controls the interpretation of values read from the system hardware clock
+CFG_LOCALTIME="/etc/localtime"         # file configures the system-wide timezone of the local system that is used by applications for presentation to the user
+TZ_DB="/usr/share/zoneinfo"            # standart path for timezone database
+TZ_DEFAULT="UTC"                       # default timezone ( use if not found the settings in the system )
+CFG_PHP="/etc/php.d/bitrixenv.ini"     # bitrixenv php file
 
 # get config form sysconfig
 get_current_timezone_from_clock() {
-  TZ_CLOCK=""
-  if [[ -f $CFG_SYSCLOCK ]]; then
-    TZ_CLOCK=$(grep -v '^#\|^$' $CFG_SYSCLOCK | awk -F'=' '/ZONE=/{print $2}' | sed -e "s:[\"\' ]::g" )
-  else
-    TZ_CLOCK="SYSCLOCK_NOT_FOUND"
-  fi
-
-  echo -n $TZ_CLOCK
-
+    TZ_CLOCK=""
+    if [[ -f $CFG_SYSCLOCK ]]; then
+	TZ_CLOCK=$(grep -v '^#\|^$' $CFG_SYSCLOCK | awk -F'=' '/ZONE=/{print $2}' | sed -e "s:[\"\' ]::g" )
+    else
+	TZ_CLOCK="SYSCLOCK_NOT_FOUND"
+     fi
+    echo -n $TZ_CLOCK
 }
 
 # get current timezone from localtime
 get_current_timzone() {
-
-  TZ_TIME=""
-
-  # link
-  if [[ -L $CFG_LOCALTIME ]]; then
-    TZ_TIME=$(readlink -f $CFG_LOCALTIME | sed -e "s:^$TZ_DB/::")
-  else
-    # file
-    if [[ -f $CFG_LOCALTIME ]]; then
-      MD5_LOCALTIME="$(md5sum $CFG_LOCALTIME | awk '{print $1}')"
-
-      # check the md5sum of all files in a directory
-      while read LINE; do
-        MD5_FOUND="$(md5sum "${LINE}" | awk '{print $1}')"
-        #echo ${LINE} ${MD5_FOUND}
-
-        if [[ "${MD5_LOCALTIME}" == "${MD5_FOUND}" ]]; then
-          TZ_TIME=$(echo "${LINE}" | sed -e "s:^$TZ_DB/::" )
-        fi
-
-      done < <( find $TZ_DB -type f )
-
-      # if not found
-      [[ -z "$TZ_TIME" ]] && TZ_TIME="LOCALTIME_NOT_FOUND"
-
-    # not exists
+    TZ_TIME=""
+    # link
+    if [[ -L $CFG_LOCALTIME ]]; then
+	TZ_TIME=$(readlink -f $CFG_LOCALTIME | sed -e "s:^$TZ_DB/::")
     else
-      TZ_TIME="LOCALTIME_NOT_FOUND"
+    # file
+	if [[ -f $CFG_LOCALTIME ]]; then
+	    MD5_LOCALTIME="$(md5sum $CFG_LOCALTIME | awk '{print $1}')"
+	    # check the md5sum of all files in a directory
+	    while read LINE; do
+		MD5_FOUND="$(md5sum "${LINE}" | awk '{print $1}')"
+		#echo ${LINE} ${MD5_FOUND}
+		if [[ "${MD5_LOCALTIME}" == "${MD5_FOUND}" ]]; then
+		    TZ_TIME=$(echo "${LINE}" | sed -e "s:^$TZ_DB/::" )
+		fi
+	    done < <( find $TZ_DB -type f )
+	    # if not found
+	    [[ -z "$TZ_TIME" ]] && TZ_TIME="LOCALTIME_NOT_FOUND"
+	    # not exists
+	else
+	    TZ_TIME="LOCALTIME_NOT_FOUND"
+	fi
     fi
-  fi
-
-  echo -n $TZ_TIME
+    echo -n $TZ_TIME
 }
 
 # get tz from bitrixenv
 get_php_tz() {
-  PHP_TZ=""
-  if [[ -f $CFG_PHP ]]; then
-    PHP_TZ=$(grep '^date.timezone' $CFG_PHP | awk -F'=' '{print $2}' | sed -s 's/^\s\+//;s/\s\+$//')
-  fi
-  if [[ -z "$PHP_TZ" ]]; then
-    echo "not_defined"
-  else
-    echo $PHP_TZ
-  fi
+    PHP_TZ=""
+    if [[ -f $CFG_PHP ]]; then
+	PHP_TZ=$(grep '^date.timezone' $CFG_PHP | awk -F'=' '{print $2}' | sed -s 's/^\s\+//;s/\s\+$//')
+    fi
+    if [[ -z "$PHP_TZ" ]]; then
+	echo "not_defined"
+    else
+	echo $PHP_TZ
+    fi
 }
-
 
 # print error message
 print_error() {
-  msg=$1
-  echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
-  exit 1
+    msg=$1
+    echo "{\"changed\":false,\"failed\":true,\"msg\":\"$msg\"}"
+    exit 1
 }
 
 # print timezone info
 print_message() {
-  tz=$1
-  tz_php=$2
-  changed=$3
-  default=$4
-
-  [[ -z "$changed" ]] && changed="false"
-  [[ -z "$default" ]] && default="false"
-
-  echo "{\"changed\":$changed,\"ansible_facts\":{\"tz\":\"$tz\",\"tz_php\":\"$tz_php\",\"tz_default\":$default}}"
-  exit 0
+    tz=$1
+    tz_php=$2
+    changed=$3
+    default=$4
+    [[ -z "$changed" ]] && changed="false"
+    [[ -z "$default" ]] && default="false"
+    echo "{\"changed\":$changed,\"ansible_facts\":{\"tz\":\"$tz\",\"tz_php\":\"$tz_php\",\"tz_default\":$default}}"
+    exit 0
 }
 
 # get ansible options
@@ -106,18 +92,17 @@ source ${1}
 
 # start process
 case $action in
-"status")
-  TZ1=$(get_current_timzone)
-  TZ2=$(get_current_timezone_from_clock)
-  TZ_PHP=$(get_php_tz)
-  
-  # test if TZ found
-  [[ $( echo "$TZ1" | grep -c 'NOT_FOUND') -eq 0 ]] && print_message "$TZ1" "$TZ_PHP"
-  [[ $( echo "$TZ2" | grep -c 'NOT_FOUND') -eq 0 ]] && print_message "$TZ2" "$TZ_PHP"
-  print_message "$TZ_DEFAULT" "$TZ_PHP" "" "true"
-;;
-*)
-  print_error "Option action=$action is not valid"
-;;
+    "status")
+	TZ1=$(get_current_timzone)
+	TZ2=$(get_current_timezone_from_clock)
+	TZ_PHP=$(get_php_tz)
+	# test if TZ found
+	[[ $( echo "$TZ1" | grep -c 'NOT_FOUND') -eq 0 ]] && print_message "$TZ1" "$TZ_PHP"
+	[[ $( echo "$TZ2" | grep -c 'NOT_FOUND') -eq 0 ]] && print_message "$TZ2" "$TZ_PHP"
+	print_message "$TZ_DEFAULT" "$TZ_PHP" "" "true"
+    ;;
+    *)
+	print_error "Option action=$action is not valid"
+    ;;
 esac
 
diff --git a/SOURCES/bitrix-env/etc/ansible/roles/web/library/bx_backup_directory b/SOURCES/bitrix-env/etc/ansible/roles/web/library/bx_backup_directory
--- a/SOURCES/bitrix-env/etc/ansible/roles/web/library/bx_backup_directory
+++ b/SOURCES/bitrix-env/etc/ansible/roles/web/library/bx_backup_directory
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/usr/bin/bash
+#
 # create directory backup and delete directory
 # directory  - path to directory that need backup
 # backup     - path where backup is saved ( default: dirname directory)
@@ -19,91 +20,91 @@ TMPDIR=/tmp
 LOGFILE=$TMP_DIR/bx_backup_directory_$$.log
 TMPFILE=$TMPDIR/bx_backup_directory_$$
 
-debug(){
-  mess=$1
-  [[ $DEBUG -gt 0 ]] && echo "$(date +%s) $mess" >> $LOGFILE
+debug() {
+    mess=$1
+    [[ $DEBUG -gt 0 ]] && echo "$(date +%s) $mess" >> $LOGFILE
 }
 
-error_message(){
-  mess=$1
-  debug "$mess"
-  echo "{\"changed\":false,\"failed\":true,\"msg\":\"$mess\"}"
-  rm -f $TMPFILE
-  exit 1
+error_message() {
+    mess=$1
+    debug "$mess"
+    echo "{\"changed\":false,\"failed\":true,\"msg\":\"$mess\"}"
+    rm -f $TMPFILE
+    exit 1
 }
 
-changed_message(){
-  mess=$1
-  file=$2
-  debug "$mess"
-  echo "{\"changed\":true,\"msg\":\"$mess\",\"archive\":\"$file\"}"
-  rm -f $TMPFILE
-  exit 0
+changed_message() {
+    mess=$1
+    file=$2
+    debug "$mess"
+    echo "{\"changed\":true,\"msg\":\"$mess\",\"archive\":\"$file\"}"
+    rm -f $TMPFILE
+    exit 0
 }
 
-notchanged_message(){
-  mess=$1
-  debug "$mess"
-  echo "{\"changed\":false,\"msg\":\"$mess\"}"
-  rm -f $TMPFILE
-  exit 0
+notchanged_message() {
+    mess=$1
+    debug "$mess"
+    echo "{\"changed\":false,\"msg\":\"$mess\"}"
+    rm -f $TMPFILE
+    exit 0
 }
 
 # test mandatory option and print error if not exists
 test_variables() {
-  # test variables
-  [[ -z "$directory" ]] && error_message "option directory= is mandatory for the plugin"
-  [[ -z "$backup" ]] && backup=$(dirname "$directory")
-  [[ -z "$delete" ]] && delete=no
-  [[ -z "$archive" ]] && archive=gzip
+    # test variables
+    [[ -z "$directory" ]] && error_message "option directory= is mandatory for the plugin"
+    [[ -z "$backup" ]] && backup=$(dirname "$directory")
+    [[ -z "$delete" ]] && delete=no
+    [[ -z "$archive" ]] && archive=gzip
 
-  debug "directory=$directory backup=$backup delete=$delete archive=$archive"
-  if [[ ! -d "$directory" ]]; then
-    notchanged_message "directory=$directory is not exist in the system"
-  fi
+    debug "directory=$directory backup=$backup delete=$delete archive=$archive"
+    if [[ ! -d "$directory" ]]; then
+	notchanged_message "directory=$directory is not exist in the system"
+    fi
 
-  # test if we can remove ( only direct path in /home/bitrix )
-  if [[ $(echo "$directory" | grep -v '\.\.' | grep -c '^/home/bitrix/\(www\|ext_www\)' ) -eq 0 ]]; then
-    notchanged_message "plugin cannot working with directory=$directory"
-  fi
+    # test if we can remove ( only direct path in /home/bitrix )
+    if [[ $(echo "$directory" | grep -v '\.\.' | grep -c '^/home/bitrix/\(www\|ext_www\)' ) -eq 0 ]]; then
+	notchanged_message "plugin cannot working with directory=$directory"
+    fi
 }
 
 # create backup for directory
 create_backup() {
-  date_mark=$(date +%Y%m%d%H%M%S)
-  util_mark="bx_backup"
+    date_mark=$(date +%Y%m%d%H%M%S)
+    util_mark="bx_backup"
 
-  tar_opt='czf'
-  tar_file=$backup/${date_mark}_${util_mark}_$(basename $directory).tar.gz
-  if [[ "$archive" == "bzip" ]]; then
-    tar_opt='cjf'
-    tar_file=$backup/${date_mark}_${util_mark}_$(basename $directory).tar.bz2
-  elif [[ "$archive" == "tar" ]]; then
-    tar_opt="cf"
-    tar_file=$backup/${date_mark}_${util_mark}_$(basename $directory).tar
-  fi
+    tar_opt='czf'
+    tar_file=$backup/${date_mark}_${util_mark}_$(basename $directory).tar.gz
+    if [[ "$archive" == "bzip" ]]; then
+	tar_opt='cjf'
+	tar_file=$backup/${date_mark}_${util_mark}_$(basename $directory).tar.bz2
+    elif [[ "$archive" == "tar" ]]; then
+	tar_opt="cf"
+	tar_file=$backup/${date_mark}_${util_mark}_$(basename $directory).tar
+    fi
 
-  if [[ -n "$backup_file" ]]; then
-    tar_file=$backup_file
-  fi
-  
-  base_directory=$(dirname "$directory")
-  name_directory=$(basename "$directory")
-  if [[ -f "$tar_file" ]]; then
-    rm -f $tar_file
-  fi
+    if [[ -n "$backup_file" ]]; then
+	tar_file=$backup_file
+    fi
 
-  tar $tar_opt "$tar_file" -C $base_directory "$name_directory" >> $TMPFILE 2>$TMPFILE
-  if [[ $? -gt 0 ]]; then
-    error_message "command tar $tar_opt on directory=$directory return error: $(tail -n 1 $TMPFILE)"
-  fi
+    base_directory=$(dirname "$directory")
+    name_directory=$(basename "$directory")
+    if [[ -f "$tar_file" ]]; then
+	rm -f $tar_file
+    fi
 
-  if [[ "$delete" == "yes" ]]; then
-    rm -rf $directory 
-    changed_message "create backup file=$tar_file and deleted directory=$directory" "$tar_file"
-  else
-    changed_message "create backup file=$tar_file" "$tar_file"
-  fi
+    tar $tar_opt "$tar_file" -C $base_directory "$name_directory" >> $TMPFILE 2>$TMPFILE
+    if [[ $? -gt 0 ]]; then
+	error_message "command tar $tar_opt on directory=$directory return error: $(tail -n 1 $TMPFILE)"
+    fi
+
+    if [[ "$delete" == "yes" ]]; then
+	rm -rf $directory
+	changed_message "create backup file=$tar_file and deleted directory=$directory" "$tar_file"
+    else
+	changed_message "create backup file=$tar_file" "$tar_file"
+    fi
 }
 
 # get options from file
